server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    root /var/www/html/public;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/$uri;
        include fastcgi_params;
    }

    # Deny access to .env and other sensitive files
    location ~ /\.env {
        deny all;
    }

    location ~ /data/ {
        deny all;
    }
}
